packages:
  - packages/*
  - packer

onlyBuiltDependencies:
  - "@biomejs/biome"
  - core-js
  - electron
  - electron-winstaller
  - simple-git-hooks

catalogs:
  packer:
    electron: ^44.5.0
    "electron-builder": ^26.15.3

catalog:
  "@rsbuild/core": ^1.3.22
  "@rslib/core": ^0.10.2
  "@types/node": ^22.15.3
  typescript: ^5.8.3

allowBuilds:
  '@biomejs/biome': true
  core-js: true
  electron: true
  electron-winstaller: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - electron@44.5.0
